runtime: nodejs18
env: standard
instance_class: F1

entrypoint: node server.js

handlers:
  - url: /static
    static_dir: client/build/static

  - url: /.*
    script: auto

env_variables:
  NODE_ENV: 'production'
